################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/cJSON/cJSON.c \
C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/cJSON/cJSON_Utils.c 

OBJS += \
./S2E_SSL_Platform/cJSON/cJSON.o \
./S2E_SSL_Platform/cJSON/cJSON_Utils.o 

C_DEPS += \
./S2E_SSL_Platform/cJSON/cJSON.d \
./S2E_SSL_Platform/cJSON/cJSON_Utils.d 


# Each subdirectory must supply rules for building sources it contributes
S2E_SSL_Platform/cJSON/cJSON.o: C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/cJSON/cJSON.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L552xx -DDEBUG '-DMBEDTLS_CONFIG_FILE=<SSLConfig.h>' -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Ethernet" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Ethernet/W5100S" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/DHCP" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/DNS" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/SNTP" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/TFTP" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Board" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Callback" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/cJSON" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Configuration" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Modbus" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/PlatformHandler" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Serial_to_Ethernet" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Security/SSLTLS/mbedtls/include" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Security/SSLTLS" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/MQTT" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/MQTT/MQTTPacket" -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"S2E_SSL_Platform/cJSON/cJSON.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
S2E_SSL_Platform/cJSON/cJSON_Utils.o: C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/cJSON/cJSON_Utils.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L552xx -DDEBUG '-DMBEDTLS_CONFIG_FILE=<SSLConfig.h>' -c -I../Core/Inc -I../../Secure_nsclib -I../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Include -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Ethernet" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Ethernet/W5100S" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/DHCP" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/DNS" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/SNTP" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/TFTP" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Board" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Callback" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/cJSON" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Configuration" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Modbus" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/PlatformHandler" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/S2E_SSL_Platform/Serial_to_Ethernet" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Security/SSLTLS/mbedtls/include" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Security/SSLTLS" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/MQTT" -I"C:/Users/Hoon-Mac/Documents/Work/Project/S2E_SSL/STM32CubeIDE/workspace_1.5.0/WIZ510SSL/ioLibrary_Driver/Internet/MQTT/MQTTPacket" -O3 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"S2E_SSL_Platform/cJSON/cJSON_Utils.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

